import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";
import "@/app/styles/globals.css";
import Home from "./Home/home";


export const metadata: Metadata = {
  title: "FreshParis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body>
      <Navbar />
      <main className="pt-16">{children}</main> {/* Add padding to prevent content from being hidden */}
      <Footer />
      </body>
      </html>
  );
}
